### ISSUE TITLE
Missing License file - repo

### ISSUE THREAD

**Issue by mbiesiad** [CVEProject/Ideas#12]
# Proposed New Idea/Feature (required)
Hi, I can not see here LICENSE file. It would be nice to add this to the repo.

# Additional Notes (Optional)
Useful resources:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Best wishes,

**Comment by zmanion** [comment]
This is technically easy but:
1. There really isn't anything in this repo other than issues, i.e., no content or documents.
2. These may apply: https://www.cve.org/Legal/TermsOfUse (and might be the LICENSE)

**Comment by mbiesiad** [comment]
Hi @zmanion Thank you for your comment and time. 
Sure, thanks. I bet many can have or had similar ideas, so now they can check this issue to get an answer.
Best regards,
