### ISSUE TITLE
Missing Code of Conduct [Feature Req]

### ISSUE THREAD

**Issue by mbiesiad** [CVEProject/Ideas#13]
# Proposed New Idea/Feature (required)
Could be added `Code of Conduct`.
As a part of Open Source - it's quite useful. After some time, when will be more contributors here, it would be nice to let people to know about wanted behavior, as well as unwanted.
Let's image situation where some of the user will be aggressive against to others - thanks to this will be well-known reason of block / give some kind of restrictions.

# Additional Notes (Optional)
It's quite popular in Open Source Community.
I'm sure that there are many templates, but I think it could contain elements like:
Please be: professional, friendly, not aggressive. (respect each other)
(or similar)

Additional information:
"A code of conduct defines standards for how to engage in a community. It signals an inclusive environment that respects all contributions" - https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project

(repo has own goal, not vulgar comments for example)

Best wishes,

**Comment by zmanion** [comment]
It's here: https://www.cve.org/resourcessupport/allresources/professionalcodeofconduct

We'll probably handle this like the LICENSE issue, perhaps standard files that contain or reference the CVE Program documents.

**Comment by mbiesiad** [comment]
Hi @zmanion Thank you for your comment and time.
For others, "handle this like the LICENSE issue" it's reference to the:
https://github.com/CVEProject/Ideas/issues/12  I suppose
Sure, thanks. I bet many can have or had similar ideas, so now they can check this issue to get an answer.
Best regards,
